// Preset object names for building "hidden object" clues in the admin scene
// editor. Grouped by category; names are used as the default clue name.
export const OBJECT_LIBRARY: { category: string; items: string[] }[] = [
  {
    category: "Nature & Landscape",
    items: [
      "Sun",
      "Desert sand dunes",
      "Palm trees",
      "Oasis vegetation",
      "Rocks",
      "Sky",
      "Clouds",
    ],
  },
  {
    category: "Buildings & Structures",
    items: [
      "Dubai skyline",
      "Burj Khalifa",
      "Traditional fort walls",
      "Large entrance gate",
      "Traditional buildings",
      "Market stalls",
      "Food truck / ice cream truck",
      "Large Bedouin tent",
      "Outdoor majlis seating tent",
      "Tables",
      "Wooden display counters",
    ],
  },
  {
    category: "Animals",
    items: [
      "Falcon",
      "Two camels",
      "Horse with rider",
      "Lizard",
      "Small desert fox",
      "Birds (flying)",
      "Gecko on the sand",
    ],
  },
  {
    category: "Vehicles",
    items: ["Red sports car", "Food truck", "Drone", "Bicycle"],
  },
  {
    category: "Flying Objects",
    items: ["Kite", "Hot air balloon", "Drone"],
  },
  {
    category: "People & Activities",
    items: [
      "Men in kandura",
      "Women in abaya",
      "Children",
      "Tourists",
      "Chef",
      "Police officer",
      "Runner",
      "Camel handler",
      "Horse rider",
      "Food vendor",
      "Coffee server",
      "Balloon seller",
      "Tourist reading map",
      "People sitting in majlis",
      "Children playing football",
      "Family walking",
      "People shopping",
      "People eating",
      "People drinking coffee",
      "Person waving UAE flag",
      "Person flying kite",
    ],
  },
  {
    category: "Traditional UAE Objects",
    items: [
      "Dallah (Arabic coffee pot)",
      "Incense burner",
      "Lanterns",
      "Dates",
      "Arabic carpets",
      "Cushions",
      "Traditional majlis sofas",
      "Decorative chests",
      "Pottery",
      "Traditional coffee cups",
      "Serving trays",
    ],
  },
  {
    category: "Market Items",
    items: [
      "Fruits (dates)",
      "Baskets",
      "Wooden bowls",
      "Model dhow boats",
      "Oud (musical instrument)",
      "Hanging lamps",
      "Hanging pottery",
      "Bottles",
      "Handicrafts",
      "Henna display",
    ],
  },
  {
    category: "Food & Cooking",
    items: [
      "Barbecue grill",
      "Skewers",
      "Plates of food",
      "Tea set",
      "Coffee cups",
      "Cooking utensils",
    ],
  },
  {
    category: "Furniture",
    items: [
      "Tables",
      "Chairs",
      "Sofas",
      "Cushions",
      "Rugs",
      "Wooden benches",
      "Wooden crates",
    ],
  },
  {
    category: "Toys & Recreation",
    items: ["Football (soccer ball)", "Balloons", "Kite"],
  },
  {
    category: "Clothing & Accessories",
    items: [
      "Kanduras",
      "Abayas",
      "Headscarves",
      "Sunglasses",
      "Backpack",
      "Handbag",
      "Briefcase",
    ],
  },
  {
    category: "Small Decorative Objects",
    items: [
      "Lanterns",
      "Hanging ornaments",
      "Treasure chest",
      "Water bottles",
      "Cups",
      "Plates",
      "Serving tray",
      "Rope decorations",
    ],
  },
  {
    category: "Flags",
    items: ["UAE flag"],
  },
];
